on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    name: Build TypeScript
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    outputs:
      output: ${{ steps.copy.outputs.release }}
    steps:
      - uses: actions/checkout@v2
      - name: Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: Build
        run: tools/build_dist.sh release
      - id: copy
        run: cp dist/release.js "$GITHUB_OUTPUT"
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            This release was automatically generated by GitHub Actions based on the tag ${{ github.ref }}.
          draft: false
          prerelease: false
  upload:
    name: Upload Build Asset
    needs: [build, release]
    runs-on: ubuntu-latest
    steps:
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ${{ needs.build.outputs.output }}
          asset_name: backend.js
          asset_content_type: text/javascript